version: "2.4"
services:
  tailscale:
    hostname: aither                         # This will become the tailscale device name
    image: tailscale/tailscale:stable
    volumes:
      - "./tailscale_var_lib:/var/lib"        # State data will be stored in this directory
      - "/dev/net/tun:/dev/net/tun"           # Required for tailscale to work
    cap_add:                                    # Required for tailscale to work
      - net_admin
      - sys_module
    privileged: true
#    environment:
#      - TAILSCALE_AUTH_KEY=tskey-auth-kUBxFU5CNTRL-GGAfhPhcZoANDduorkPJiAenZSuB9ixpX
    env_file:
      - tailscale.env
    ports:
      - 5900:5900
      - 5901:5901
      - 5902:5902
      - 5903:5903
      - 5904:5904
      - 5905:5905
      - 5906:5906
      - 5907:5907
      - 5908:5908
      - 5909:5909
      - 5910:5910
      - 7023:7023
    command: tailscaled

  aither:
    image: aither-baseimage
    build: .
    container_name: aither-baseimage
    privileged: true #optional
    environment:
    #  - PUID=1000
    #  - PGID=1000
    #  - TZ=US/Central  
      - XDG_RUNTIME_DIR=/home/dev
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY 
      - WLR_BACKENDS=headless
      - WLR_LIBINPUT_NO_DEVICES=1 
      - --user= dev
    command: dbus-run-session -- sway
    user: dev
    tty: true
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #optional
      - $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/home/1000/$WAYLAND_DISPLAY
#    ports:
#      - 5900:5900
#      - 5901:5901
#      - 5902:5902
#      - 5903:5903
#      - 5904:5904
#      - 5905:5905
#      - 5906:5906
#      - 5907:5907
#      - 5908:5908
#      - 5909:5909
#      - 5910:5910
#     - 7023:7023
    network_mode: service:tailscale
    #shm_size: "1gb" #optional
    #restart: unless-stopped
