version: "2.4"
services:
  tailscale:
    hostname: aither                         # This will become the tailscale device name
    image: tailscale/tailscale:stable
    volumes:
      - "./tailscale_var_lib:/var/lib"       # State data will be stored in this directory
      - "/dev/net/tun:/dev/net/tun"          # Required for tailscale to work
    cap_add:                                 # Required for tailscale to work
      - net_admin
      - sys_module
    privileged: true
    env_file:
      - tailscale.env
    ports:
      - 6080:6080
      - 6081:6081
      - 6082:6082
      - 6083:6083
      - 6084:6085
      - 6086:6086
      - 6087:6087
      - 6088:6088
      - 6089:6089
      - 6090:6090
      - 8080:8080
    command: tailscaled

  s3fs:
    container_name: s3fs
    privileged: true
    image: efrecon/s3fs:1.91
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    security_opt:
      - 'apparmor:unconfined'
    devices:
      - /dev/fuse
    volumes:
      - './bucket:/opt/s3fs/bucket:rshared'
    environment:
      AWS_S3_BUCKET: '<BUCKET_NAME>'
      AWS_S3_ACCESS_KEY_ID: '<ACCESS_KEY_ID>'
      AWS_S3_SECRET_ACCESS_KEY: '<SECRET_ACCESS_KEY_ID>'
      AWS_S3_MOUNT: '/opt/s3fs/bucket'
      S3FS_ARGS: ''
      S3FS_DEBUG: 0
      UID: 1000
      GID: 1000
    depends_on:
      - aither
    network_mode: service:tailscale

  aither:
    image: enokiinc/aither
#    build: .
    container_name: aither-baseimage
    privileged: true #optional
    environment:
      - XDG_RUNTIME_DIR=/home/dev
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY 
      - WLR_BACKENDS=headless
      - WLR_LIBINPUT_NO_DEVICES=1 
      - --user= dev
    command: dbus-run-session -- sway
    user: dev
    tty: true
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #optional
      - $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/home/1000/$WAYLAND_DISPLAY
      - ./bucket:/s3:rshared
#    ports:
#      - 6080:6080
#      - 6081:6081
#      - 6082:6082
#      - 6083:6083
#      - 6084:6085
#      - 6086:6086
#      - 6087:6087
#      - 6088:6088
#      - 6089:6089
#      - 6090:6090
    network_mode: service:tailscale
    #shm_size: "1gb" #optional
    #restart: unless-stopped
